---
title: "Kaggle Tatanic"
output: html_notebook
---

```{r load_library }

load.libraries <- c('tidyverse','data.table','mice', 'randomForest')
install.lib <- load.libraries[!load.libraries %in% installed.packages()]
for(libs in install.lib) install.packages(libs, dependences = TRUE)
sapply(load.libraries, require, character = TRUE)

```

```{r load_datasets}
train <- as.tibble(fread("train.csv"))
test <- as.tibble(fread("test.csv"))
full <- bind_rows(train,test)
```

```{r check_data_structure}
str(full)
```

```{r show_na_values}
colSums(sapply(full, is.na))
```



```{r}
train %>% ggplot(aes(as.factor(Survived))) + geom_bar() + geom_text(stat='count', aes(label=..count..), vjust=-0.5)
```
```{r}
train %>% filter(Fare < 300) %>% ggplot(aes(Fare)) + geom_histogram(aes(fill = as.factor(Survived)), binwidth = 5)
```

```{r}
train %>% ggplot(aes(as.factor(Pclass))) + geom_bar(aes(fill = as.factor(Survived)))
```

```{r}
full %>% group_by(Ticket) %>% mutate(n = n(), p = median(Fare), FarePerPerson = p/n) %>% filter(!is.na(Survived)) %>%ggplot(aes(FarePerPerson)) + geom_histogram(aes(fill=as.factor(Survived)), binwidth = 5)
```

```{r}
full <- full %>% group_by(Ticket) %>% mutate(n = n(), p = median(Fare), FarePerPerson = p/n)
```

```{r}
full <- full %>% mutate(NotAlone = ifelse(n > 1 , 1, 0))
```

```{r}
full$n = NULL
full$p = NULL
```
```{r}
full %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n = n()) %>% filter(n>1)
```

```{r}
multiCabin <- full %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n = n()) %>% filter(n > 1)
```
```{r}
singleCabin <- full %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n = n()) %>% filter(n == 1)
```

```{r}
full %>% filter(Cabin %in% singleCabin$Cabin)
```

```{r}
full <- full %>% mutate(CabinMore = ifelse(Cabin %in% multiCabin$Cabin, 1,0))
```
```{r}
full <- full %>% mutate(CabinOne = ifelse(Cabin %in% singleCabin$Cabin, 1,0))
```

```{r}
head(full)
```

```{r}
train %>% ggplot(aes(as.factor(Embarked))) + geom_bar(aes(fill=as.factor(Survived))) + geom_text(stat='count', aes(label=..count..), vjust=-0.5)
```

```{r}
train_complete_notalone <- train %>% group_by(Ticket) %>% summarise(n=n(), NumSurvived = sum(Survived)) %>% filter(!(Ticket %in% (test$Ticket))) %>% filter(n>1)
```
```{r}
 train %>% group_by(Ticket) %>% summarise(n=n(), NumSurvived = sum(Survived)) %>% filter(!(Ticket %in% (test$Ticket))) %>% filter(n==1)
```

```{r}
train %>% group_by(Ticket) %>% summarise(n=n(), NumSurvived = sum(Survived)) %>% filter(!(Ticket %in% (test$Ticket))) %>% filter(n ==1) %>% ggplot(aes(as.factor(NumSurvived))) + geom_bar()
```

```{r}
train %>% filter(Ticket %in% train_complete_notalone$Ticket) %>% select(-PassengerId,-Name)
```

```{r}
train %>% filter(Ticket %in% train_complete_notalone$Ticket) %>% select(-PassengerId,-Name) %>% ggplot(aes(as.factor(Sex)))+ geom_bar(aes(fill=as.factor(Survived)))
```

```{r}
train_complete_wholeCabin <- train %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n=n(), NumSurvived = sum(Survived)) %>% filter (!(Cabin %in% (test$Cabin))) %>% filter(n>1)
```

```{r}
train %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n=n(), NumSurvived = sum(Survived)) %>% filter (!(Cabin %in% (test$Cabin))) %>% filter(n==1) %>% ggplot(aes(as.factor(NumSurvived))) + geom_bar()
```

```{r}
train %>% filter(Cabin %in% train_complete_wholeCabin$Cabin & Cabin != "") %>% select(-PassengerId,-Name)
```

```{r}
train %>% filter(Ticket %in% train_complete_notalone$Ticket) %>% select(-PassengerId,-Name) %>% ggplot(aes(as.factor(Sex)))+ geom_bar(aes(fill=as.factor(Survived)))
```


```{r}
allSurvive <- train %>% filter(Cabin != "")  %>% group_by(Cabin) %>% summarise(n=n(),Survive = sum(Survived)) %>% mutate(all_survive = as.integer(n == Survive))
sum(allSurvive$all_survive)
```

```{r}
full %>% filter(Cabin != "")  %>% group_by(Cabin) %>% summarise(n=n(),Survive = sum(Survived)) %>% filter(!is.na(Survive)) %>% filter(n > 1) 
```

```{r}
not_all_survived <- full %>% filter(Cabin != "")  %>% group_by(Cabin) %>% summarise(n=n(),Survive = sum(Survived)) %>% filter(!is.na(Survive)) %>% filter(n > 1) %>% filter(n!= Survive)
```

```{r}
train %>% filter(Cabin %in% as.vector(not_all_survived$Cabin)) %>% select(Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare, Cabin,Embarked)
```

```{r}
train %>% filter(Cabin != "") %>% group_by(Cabin) %>% summarise(n=n(), Survive = sum(Survived)) %>% filter(n == 1) %>% ggplot(aes(Survive)) + geom_bar()
```

```{r}
sum(as.integer(test$Cabin != ""))
```

```{r}
train %>% filter(Cabin != "") %>% ggplot(aes(Survived)) + geom_bar()
```

```{r}
full %>% group_by(Ticket) %>% mutate(n = n(), p = median(Fare), FarePerPerson = p/n) %>% filter(!is.na(Survived)) %>%ggplot(aes(FarePerPerson)) + geom_histogram(aes(fill=as.factor(Survived)), binwidth = 5)
```


```{r}
train %>% ggplot(aes(Survived)) + geom_bar()
```

```{r}
full <- full %>% mutate(Embarked = ifelse(Embarked == "", "C", Embarked))
```




```{r show_null_values}
colSums(sapply(full, function(x){!is.na(x) & x==""}))
```



```{r}
median_fare <- full %>% filter(Pclass == 3 & Embarked == 'S' & FamilySize == 1) %>% select(Fare) %>% .[[1]] %>% as.vector() %>% median(na.rm= T)
full <- full %>% mutate(Fare = ifelse(is.na(Fare), median_fare, Fare))
```

```{r}
full %>% filter(Embarked == "")
```


```{r}
full %>% filter(Pclass == 1) %>% arrange(desc(Fare))
```

```{r }
full <- full %>% mutate(FamilySize = SibSp + Parch + 1)
```


```{r}
full %>% filter(FamilySize > 1 & is.na(Age)) 
```

```{r}
full <- full %>% mutate(Surname = gsub(",.*\\..*","",Name))
```

```{r}
full <- full %>% mutate(Title = trimws(gsub("(.*,)|(\\..*)","",Name)))
```

```{r}
full %>% filter(FamilySize > 1) %>% arrange(FamilySize,Surname) %>% select(PassengerId,Survived,Sex,Age,SibSp,Parch,FamilySize,Surname,Title)
```

```{r}
full <- full %>% mutate(IsMother = ifelse(Sex == 'female' & Parch >0 & Age > 18 & Title != 'Miss', 1, 0))

```




```{r}
full <- full %>% mutate(IsAdult = ifelse(Age >= 18 | FamilySize == 1 | Title == 'Mrs', 1, 0))
```

```{r}
full <- full %>% mutate(IsAdult = replace(IsAdult, IsMother == 0 & Sex == 'female' & Parch > 0 & is.na(Age), 0)) 
```

```{r}
full <- full %>% mutate(IsAdult = replace(IsAdult, is.na(IsAdult) & is.na(Age), 0)) 
```


```{r}
full <- full %>% mutate(IsMother = replace(IsMother, is.na(IsMother), 1)) 
```

```{r}
full %>% filter(IsAdult == 0)
```


```{r}
full %>% filter(is.na(IsAdult)) %>% arrange(desc(SibSp))
```


```{r}
full %>% filter(FamilySize == 4) %>% arrange(FamilySize,Surname) %>% select(PassengerId,Survived,Sex,Age,SibSp,Parch,FamilySize,Surname,Title)
```


```{r}
full %>% filter(FamilySize >1) %>% group_by(Surname) %>% summarise(FamilySize = max(FamilySize), TotalSurvived = sum(Survived)) %>% filter(TotalSurvived > 0) %>% mutate(whole = ifelse(FamilySize == TotalSurvived, 1 , 0))
```


```{r}
full %>% filter(PassengerId<=891) %>% ggplot(aes(x=Age, fill= as.factor(Survived))) + geom_histogram(binwidth=9)



```
```{r}

```


```{r}
age_data <- full %>% select(PassengerId,Pclass,Sex,Age,SibSp,Parch,Embarked, FamilySize,IsMother, IsAdult)
```

```{r}
kids_data <- age_data %>% filter(IsAdult == 0)
Adults_data <- age_data %>% filter(IsAdult == 1)
```

```{r}
kids_data %>% ggplot(aes(Age)) + geom_histogram(binwidth = 2)
```
```{r}
kids_output %>% ggplot(aes(Age)) + geom_histogram(binwidth = 2)
```


```{r}
set.seed(123)
mice_kids <- mice(kids_data,method = "rf")
mice_adults <- mice(Adults_data, method = "rf")
```


```{r}
kids_output <- complete(mice_kids)
adults_output <- complete(mice_adults)
```


```{r}
data <- bind_rows(kids_output,adults_output)
data <- data %>% arrange(PassengerId)
data$Survived <- full$Survived

```


```{r}
full$Age <- data$Age
```

```{r}
data$Sex <- factor(data$Sex)
data$Embarked <- factor(data$Embarked)
```

```{r}
train_data <- data %>% filter(PassengerId <= 891)
test_data <- data %>% filter(PassengerId > 891)
```


```{r}
colSums(sapply(train_data, is.na))
```

```{r}
classifier <- randomForest(factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + 
                                            Embarked + 
                                            FamilySize + IsMother + IsAdult,
                                            data = train_data)
```


```{r}
plot(classifier, ylim=c(0,0.36))
```



```{r}
prediction <- predict(classifier, test_data)
```

```{r}
solution <- data.frame(PassengerID = test_data$PassengerId, Survived = prediction)
write.csv(solution, file = 'Submission1.csv', row.names = F)
```







